In [39]:
import numpy as np
from sklearn import preprocessing


In [23]:
df = np.loadtxt('C:Documents/books_data.csv', delimiter = ',')

In [24]:
df

array([[9.9400e+02, 1.6200e+03, 1.6200e+03, ..., 5.0000e+00, 9.2000e+01,
        0.0000e+00],
       [1.1430e+03, 2.1600e+03, 2.1600e+03, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [2.0590e+03, 2.1600e+03, 2.1600e+03, ..., 0.0000e+00, 3.8800e+02,
        0.0000e+00],
       ...,
       [3.1134e+04, 2.1600e+03, 2.1600e+03, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [3.2832e+04, 1.6200e+03, 1.6200e+03, ..., 0.0000e+00, 9.0000e+01,
        0.0000e+00],
       [2.5100e+02, 1.6740e+03, 3.3480e+03, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00]])

extract inputs and targets

In [25]:
#to extract the input columns
input_unscaled = df[:,1:-1]
target_un = df[:,-1]

Balance the dataset

In [26]:
#balance the dataset
#count the targets that are 1
num_of_one = int(np.sum(target_un))
#initializing the  zero counter to zero
zero_counter = 0
#creating an empty list for numbers to be removed
removed = []


for i in range(target_un.shape[0]):
    if target_un[i] == 0:
        zero_counter =+ 1
        if zero_counter > num_of_one:
            removed.append[i]
            
            
#to remove the uneven dataset
input_unscaled_equal = np.delete(input_unscaled, removed, axis=0)
target_equal = np.delete(target_un, removed, axis=0)




In [27]:
target_equal


array([0., 0., 0., ..., 0., 0., 1.])

Standardize the inputs

In [29]:
#we standadize the inputs using preprocessing
scaled_inputs = preprocessing.scale(input_unscaled_equal)

In [31]:
scaled_inputs

array([[ 0.05694432, -0.08950406,  2.56031917, ...,  3.81035339,
        10.44134984,  0.34085525],
       [ 1.12768719,  0.7351559 , -0.359686  , ..., -0.51173244,
        -0.14873032, -0.70217541],
       [ 1.12768719,  0.7351559 , -0.359686  , ..., -0.51173244,
        -0.14873032,  3.69669302],
       ...,
       [ 1.12768719,  0.7351559 , -0.19543571, ..., -0.51173244,
        -0.14873032, -0.70217541],
       [ 0.05694432, -0.08950406, -0.359686  , ...,  1.14725   ,
        -0.14873032,  0.31818067],
       [ 0.1640186 ,  2.5494078 , -0.359686  , ..., -0.51173244,
        -0.14873032, -0.70217541]])

Shuffle the data (to make sure the dataset is randomly distributed after batching)

In [33]:
shuffled_indices = np.arange(scaled_inputs.shape[0])
np.random.shuffle(shuffled_indices)

shuffled_inputs = scaled_inputs[shuffled_indices]
shuffled_targets = target_equal[shuffled_indices]

spit the dataset into train, validation, and test

In [36]:
#using the shape attribute to extract the number of rows
whole_data = shuffled_inputs.shape[0]

#spliting the rows to 80:10:10 for train:validation:test
train_samples_count = int(0.8*whole_data)
validation_samples_count = int(0.1*whole_data)
test_samples_count = whole_data - train_samples_count - validation_samples_count

#using slicing to assign the portion of row to each category
train_inputs = shuffled_inputs[:train_samples_count]
train_targets = shuffled_targets[:train_samples_count]

validation_inputs = shuffled_inputs[train_samples_count:train_samples_count+validation_samples_count]
validation_targets = shuffled_targets[train_samples_count:train_samples_count+validation_samples_count]


test_inputs = shuffled_inputs[train_samples_count+validation_samples_count:]
test_targets = shuffled_targets[train_samples_count+validation_samples_count:]


print(np.sum(train_targets), train_samples_count, np.sum(train_targets) / train_samples_count*100)
print(np.sum(validation_targets), validation_samples_count, np.sum(validation_targets) / validation_samples_count*100)
print(np.sum(test_targets), test_samples_count, np.sum(test_targets) / test_samples_count*100)

1807.0 11267 16.037987041803497
207.0 1408 14.701704545454545
223.0 1409 15.826827537260469


Save the three datasets in *.npz file format

In [37]:
np.savez("books_data_train", inputs=train_inputs, targets=train_targets)
np.savez("books_data_validation", inputs=validation_inputs, targets=validation_targets)
np.savez("books_data_test", inputs=test_inputs, targets=test_targets)